------------------------------------------
------------------------------------------
--회원정보
------------------------------------------
------------------------------------------
--DROP SEQUENCE SDUSEQ;
--DROP TABLE SDUSER;

CREATE SEQUENCE SDUSEQ;

CREATE TABLE SDUSER
(
    SDUSEQ          NUMBER           NOT NULL, 
    SDUEAMIL        VARCHAR2(100)    NOT NULL, 
    SDUPW           VARCHAR2(100)    NOT NULL, 
    SDUNAME         VARCHAR2(200)    NULL, 
    SDUSEX          VARCHAR2(5)      NULL, 
    SDUNICK         VARCHAR2(200)    NULL, 
    SDUDOB          DATE             NULL, 
    SDUDEACT        VARCHAR2(5)      NULL, 
    SDUGRADE        VARCHAR2(20)     NULL, 
    SDUDEACTDATE    DATE             NULL, 
    SDUREGDATE      DATE             NULL, 
    CONSTRAINT SDUSER_PK PRIMARY KEY (SDUEAMIL)
);
/

INSERT INTO SDUSER VALUES
(SDUSEQ.NEXTVAL, 'abc123@gmail.com', 1234, 'abc초콜릿', 'M', '초코초코', '2010-10-10', 'N', 'U', null, SYSDATE);

INSERT INTO SDUSER VALUES
(SDUSEQ.NEXTVAL, 'abc456@gmail.com', 1234, 'abc초콜릿', 'M', '초코초코', '2010-10-10', 'N', 'U', null, SYSDATE);

SELECT * FROM SDUSER;

COMMENT ON TABLE SDUSER IS '회원'
/

COMMENT ON COLUMN SDUSER.SDUSEQ IS '유저시퀀스'
/

COMMENT ON COLUMN SDUSER.SDUEAMIL IS '아이디'
/

COMMENT ON COLUMN SDUSER.SDUPW IS '비번'
/

COMMENT ON COLUMN SDUSER.SDUNAME IS '이름'
/

COMMENT ON COLUMN SDUSER.SDUSEX IS '성별'
/

COMMENT ON COLUMN SDUSER.SDUNICK IS '닉네임'
/

COMMENT ON COLUMN SDUSER.SDUDOB IS '생년월일'
/

COMMENT ON COLUMN SDUSER.SDUDEACT IS '탈퇴여부'
/

COMMENT ON COLUMN SDUSER.SDUGRADE IS '회원등급'
/

COMMENT ON COLUMN SDUSER.SDUDEACTDATE IS '탈퇴날짜'
/

COMMENT ON COLUMN SDUSER.SDUREGDATE IS '가입날짜'
/

------------------------------------------
------------------------------------------
--게시판
------------------------------------------
------------------------------------------
--DROP SEQUENCE SDBSEQ;
--DROP SEQUENCE SDBGROUPSEQ;
CREATE SEQUENCE SDBSEQ;
CREATE SEQUENCE SDBGROUPSEQ;

CREATE TABLE SDBOARD
(
    SDBSEQ         NUMBER            NOT NULL, 
    SDBTABNO       NUMBER            NULL, 
    SDBGROUPSEQ    NUMBER            NULL, 
    SDBGROUPNO     NUMBER            NULL, 
    SDBTITLE       VARCHAR2(200)     NULL, 
    SDUEAMIL       VARCHAR2(100)     NOT NULL, 
    SDUB           VARCHAR2(4000)    NULL, 
    SDBREGDATE     DATE              NULL, 
    SDBVIEWS       NUMBER            NULL, 
    SDBLIKE        NUMBER            NULL, 
    SDBFILENAME    VARCHAR2(200)     NULL, 
    SDBFILPATH     VARCHAR2(2000)    NULL, 
    CONSTRAINT SDBOARD_PK PRIMARY KEY (SDBSEQ)
);
/

COMMENT ON TABLE SDBOARD IS '게시판'
/

COMMENT ON COLUMN SDBOARD.SDBSEQ IS '글시퀀스'
/

COMMENT ON COLUMN SDBOARD.SDBTABNO IS '탭번호'
/

COMMENT ON COLUMN SDBOARD.SDBGROUPSEQ IS '그룹시퀀스'
/

COMMENT ON COLUMN SDBOARD.SDBGROUPNO IS '그룹번호'
/

COMMENT ON COLUMN SDBOARD.SDBTITLE IS '글제목'
/

COMMENT ON COLUMN SDBOARD.SDUEAMIL IS '글 작성자'
/

COMMENT ON COLUMN SDBOARD.SDUB IS '글내용'
/

COMMENT ON COLUMN SDBOARD.SDBREGDATE IS '글작성일'
/

COMMENT ON COLUMN SDBOARD.SDBVIEWS IS '조회수'
/

COMMENT ON COLUMN SDBOARD.SDBLIKE IS '좋아요'
/

COMMENT ON COLUMN SDBOARD.SDBFILENAME IS '파일이름'
/

COMMENT ON COLUMN SDBOARD.SDBFILPATH IS '파일경로'
/

ALTER TABLE SDBOARD
    ADD CONSTRAINT FK_SDBOARD_SDUEAMIL_SDUSER_SDU FOREIGN KEY (SDUEAMIL)
        REFERENCES SDUSER (SDUEAMIL);
/

------------------------------------------
------------------------------------------
--달력일정
------------------------------------------
------------------------------------------

CREATE SEQUENCE SDCSEQ;

CREATE TABLE SDCALENDAR
(
    SDCSEQ         NUMBER            NOT NULL, 
    SDCTITLE       VARCHAR2(200)     NULL, 
    SDCCONTENT     VARCHAR2(4000)    NULL, 
    SDCSARTDATE    DATE              NULL, 
    SDCENDDATE     DATE              NULL, 
    SDUEAMIL       VARCHAR2(100)     NOT NULL, 
    CONSTRAINT SDCALENDAR_PK PRIMARY KEY (SDCSEQ)
);
/

COMMENT ON TABLE SDCALENDAR IS '일정_달력'
/

COMMENT ON COLUMN SDCALENDAR.SDCSEQ IS '일정시퀀스'
/

COMMENT ON COLUMN SDCALENDAR.SDCTITLE IS '일정제목'
/

COMMENT ON COLUMN SDCALENDAR.SDCCONTENT IS '일정내용'
/

COMMENT ON COLUMN SDCALENDAR.SDCSARTDATE IS '일정시작날짜'
/

COMMENT ON COLUMN SDCALENDAR.SDCENDDATE IS '일정끝날짜'
/

COMMENT ON COLUMN SDCALENDAR.SDUEAMIL IS '일정 작성자'
/

ALTER TABLE SDCALENDAR
    ADD CONSTRAINT FK_SDCALENDAR_SDUEAMIL_SDUSER_ FOREIGN KEY (SDUEAMIL)
        REFERENCES SDUSER (SDUEAMIL);
/